name: file_icon
description: File icons for different file types, auto detected by file name.
version: 0.4.0
homepage: https://github.com/pd4d10/file-icon

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Seti
      fonts:
        - asset: fonts/seti.ttf
